plugins {
    id 'java-library'
    id 'maven-publish'
}

base.archivesName = mod_id
version = minecraft_version + '-' + mod_version
group = maven_group

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = project.hasProperty('jvm') ? jvm as Integer : 21
}

java {
    withSourcesJar()
}

base {
    version = "$version-$name"
}

ext {
    mod_meta = [
            'mod_name'         : project_name,
            'mod_author'       : mod_author,
            'version'          : version,
            'mcversion'        : minecraft_version,
            'homepage_fabric'  : findProperty('curse_page_fabric') ?: '',
            'fabric_version'   : fabric_version,
            'loader_version'   : neo_loader_version,
            'homepage_neoforge': findProperty('curse_page_forge') ?: '',
            'neoforge_version' : neoforge_version
    ]
}

repositories {
    maven {
        name = "Parchment MC"
        url = 'https://maven.parchmentmc.org'
        content {
            includeGroupAndSubgroups('org.parchmentmc')
        }
    }
}

sourcesJar {
    var license = rootProject.file('LICENSE');
    if (license.exists()) {
        from(rootProject.file('LICENSE'))
    }
}

jar {
    var license = rootProject.file('LICENSE');
    if (license.exists()) {
        from(rootProject.file('LICENSE'))
    }

    manifest {
        attributes([
                'Specification-Title'   : mod_meta.mod_name,
                'Specification-Vendor'  : mod_meta.mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_meta.mod_author,
                'Built-On-Minecraft'    : minecraft_version,
        ])
    }
}

processResources {
    inputs.property 'version', version

    filesMatching(['fabric.mod.json', 'META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand mod_meta
    }
    exclude '.cache'
}

// By default runtimeElements contain both apiElements (from api dependency and runtimeElements (from runtimeOnly dependency)
// This snippet instead makes it so (under the assumption that runtimeOnly dependencies are optional)
// only required runtime dependency (from api and implementation) are exposed to the consumer
// Users can still access the complete dependency by requiring the full capability as seen below
configurations {
    runtimeElements {
        // Make the default elements require a capability
        outgoing {
            capability("${group}:${mod_id}-full:${version}")
        }
    }
    requiredRuntime {
        extendsFrom api
        extendsFrom implementation
        // Copy additional data from runtimeElements
        attributes {
            configurations.runtimeElements.attributes.keySet().each { att ->
                it.attribute(att, configurations.runtimeElements.attributes.getAttribute(att))
            }
        }
        outgoing {
            configurations.runtimeElements.outgoing.artifacts.configureEach { art ->
                it.artifact(art)
            }
        }
    }
}

AdhocComponentWithVariants javaComponent = (AdhocComponentWithVariants) components.java
// Make runtimeElements be optional by default
javaComponent.withVariantsFromConfiguration(configurations.runtimeElements, {
    mapToOptional()
})
javaComponent.addVariantsFromConfiguration(configurations.requiredRuntime, {
    mapToMavenScope("runtime")
})
// ==========

publishing {
    repositories {
        def token = project.findProperty('maven.token') ?: System.getenv('BLAZING_COOP_MAVEN_TOKEN')
        if (token) {
            maven {
                url = 'https://maven.blazing-coop.net/releases'
                credentials {
                    username = project.findProperty('maven.user') ?: System.getenv('BLAZING_COOP_MAVEN_USER')
                    password = token
                }
            }
        }
        token = project.findProperty('gpr.gitlab.token') ?: System.getenv('GPR_GITLAB_TOKEN')
        if (token) {
            maven {
                url = 'https://gitlab.com/api/v4/projects/21830712/packages/maven'
                credentials {
                    username = project.findProperty('gpr.user') ?: System.getenv('GPR_USER')
                    password = token
                }
            }
        }
    }
}
