plugins {
    id 'net.neoforged.moddev'
    id 'io.github.flemmli97.multiloader.common-convention'
}

Properties props = new Properties()
props.load(getClass().getResourceAsStream("multiloader.properties"))
println("Applying Multiloader plugin - version ${props.get('version')}")

neoForge {
    neoFormVersion = neoForm_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    validateAccessTransformers = true
}

configurations {
    // Use this configuration if the dependency is only required in common
    commonDependency {
        canBeResolved = true
    }
    compileClasspath.extendsFrom commonDependency
}

repositories {
    maven {
        name = 'Fabric'
        url = uri('https://maven.fabricmc.net')
        content {
            includeGroupAndSubgroups('net.fabricmc')
        }
    }
}

dependencies {
    // This is only here for the EnvType annotation which can be present with fabric dependencies
    commonDependency "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly("org.ow2.asm:asm-tree:9.6")
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.7'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.0'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.0'
    compileOnly(project(path: ':fabric', configuration: 'remapCommonArtifact'))
}

processResources {
    exclude '.cache'
    filesMatching('pack.mcmeta') {
        expand 'mod_name': project_name
    }
}

tasks.register('cleanLocalPublish') {
    group = 'publishing'
    dependsOn clean, publishToMavenLocal
    publishToMavenLocal.mustRunAfter clean
}

tasks.register('cleanPublish') {
    group = 'publishing'
    dependsOn clean, publish
    publish.mustRunAfter clean
}

if ((findProperty('with_publish') ?: 'true').toBoolean()) {
    tasks.register('uploadAndPublish') {
        group = 'publishing'
        dependsOn clean, publish
        publish.mustRunAfter clean
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = project.mod_id
            suppressPomMetadataWarningsFor('runtimeElements')
        }
    }
}