plugins {
    id 'io.github.flemmli97.multiloader.changelog'
}

import com.diluv.schoomp.Webhook
import com.diluv.schoomp.message.Message
import com.diluv.schoomp.message.embed.Embed

ext {
    notifications = []
}

subprojects {
    afterEvaluate {
        def uploadTask = project.tasks.findByName('upload')
        if (uploadTask != null) {
            uploadTask.finalizedBy discordNotification
        }
        def publishTask = project.tasks.findByName('uploadAndPublish')
        if (publishTask != null) {
            publishTask.finalizedBy discordNotification
        }
    }
}

//Splits the changelog into multiple parts if they get bigger than discords embed field size (1024)
def discordChangelog() {
    def changelog = changelog(1)
    def res = new ArrayList()
    if (changelog.size() < 1000) {
        res.add(changelog)
        return res
    }
    def temp = ''
    changelog.split('\n').each {
        it = it + '\n'
        if ((temp.size() + it.size()) >= 1000) {
            res.add(temp)
            temp = it
        } else {
            temp += it
        }
    }
    res.add(temp)
    return res
}

def discordNotif(List<String> loaders) {
    print("Sending notifications for loaders ${loaders}")
    try {
        def webhook = new Webhook(findProperty('discordHook'), "${project.project_name} Upload")

        def message = new Message()
        def version = project.curse_versions.split(', ')[0]
        message.setUsername('Curseforge Release')
        def content = "${project.project_name} ${project.mod_version} for Minecraft ${version} has been released!"
        if (project.hasProperty('discord_role')) {
            content = "<@&${project.discord_role}> " + content
        }
        message.setContent(content)
        message.setAvatarUrl('https://cdn.discordapp.com/avatars/680540027255652407/e4b7a058b24843ae13389a9a3cc3ae8c.png?size=128')

        def embed = new Embed()

        if (loaders.contains('fabric')) {
            def fileIDFabric = project('fabric').tasks.getByName("curseforge${project.curse_id_fabric}").property('mainArtifact').fileID
            embed.addField('Get the fabric version here (When it is accepted)', "${project.findProperty('curse_page_fabric')}/files/${fileIDFabric}", false)
            fileIDFabric = project('fabric').tasks.getByName('modrinth').property('uploadInfo').id
            embed.addField('Modrinth version (fabric)', "${project.findProperty('modrinth_page')}/version/${fileIDFabric}", false)
        }
        if (loaders.contains('forge')) {
            def fileIDForge = project('forge').tasks.getByName("curseforge${project.curse_id_forge}").property('mainArtifact').fileID
            embed.addField('Get the neoforge version here (When it is accepted)', "${project.findProperty('curse_page_forge')}/files/${fileIDForge}", false)
            fileIDForge = project('forge').tasks.getByName('modrinth').property('uploadInfo').id
            embed.addField('Modrinth version (forge)', "${project.findProperty('modrinth_page')}/version/${fileIDForge}", false)
        }
        if (loaders.contains('neoforge')) {
            def fileIDForge = project('neoforge').tasks.getByName("curseforge${project.curse_id_forge}").property('mainArtifact').fileID
            embed.addField('Get the neoforge version here (When it is accepted)', "${project.findProperty('curse_page_forge')}/files/${fileIDForge}", false)
            fileIDForge = project('neoforge').tasks.getByName('modrinth').property('uploadInfo').id
            embed.addField('Modrinth version (neoforge)', "${project.findProperty('modrinth_page')}/version/${fileIDForge}", false)
        }
        def changelog = discordChangelog()
        if (changelog.size() == 1) {
            embed.addField('Change Log', "```md\n${changelog.get(0) ?: 'Unavailable :('}```", false)
        } else {
            changelog.forEach {
                embed.addField('Change Log', "```md\n${it}```", false)
            }
        }
        embed.setColor(0xFF8000)
        message.addEmbed(embed)

        webhook.sendMessage(message)
    } catch (IOException e) {
        println 'Failed to push to the Discord webhook. ' + e
    }
}

tasks.register('discordNotification') {
    doLast {
        discordNotif(notifications)
    }
}