plugins {
    id 'io.github.flemmli97.multiloader.changelog'
    id 'io.github.flemmli97.multiloader.common-convention'
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        useLegacyMixinAp = false
    }
    runs {
        client {
            client()
            vmArgs '-Dmixin.debug.export=true'
        }
        server {
            server()
        }
    }
}

configurations {
    // Configuration that allows using intermediary mapped mods in common
    remapCommon {
        canBeConsumed = true
    }
    remapCommonArtifact {
        canBeConsumed = true
    }
    // Add fabric configurations
    requiredRuntime {
        extendsFrom api
        extendsFrom implementation
        outgoing {
            // Remove the unmapped dev jar from artifacts
            it.artifacts.removeIf {
                return it.classifier == "dev"
            }
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${propertyWithFallback("fabric_api_version", "fabric_version")}"
    compileOnly(project(':common'))
    compileOnly(project(path: ':common', configuration: 'commonDependency'))
}

// Fetches remapped artifacts and adds them to the common dependencies
afterEvaluate {
    artifacts {
        configurations.named("compileClasspath").get().resolvedConfiguration.resolvedArtifacts.stream()
                .filter { artifact ->
                    configurations.named("remapCommon").get().incoming.dependencies.any {
                        artifact.moduleVersion.id.group.contains(it.group)
                                && artifact.moduleVersion.id.name.startsWith(it.name)
                                && artifact.moduleVersion.id.version == it.version
                    }
                }.each { add("remapCommonArtifact", it.file) }
    }
}

processResources {
    from(project(":common").sourceSets.main.resources)
    exclude '**/accesstransformer.cfg'
}

tasks.named('compileJava', JavaCompile) {
    source(project(":common").sourceSets.main.allSource)
}

tasks.named('sourcesJar', Jar) {
    from(project(":common").sourceSets.main.allSource)
    exclude '.cache'
}

def propertyWithFallback(String name, String fallback) {
    return project.hasProperty(name) ? project."${name}" : project."${fallback}"
}

var hasCurseforge = tasks.findByName("curseforge") != null
if (hasCurseforge) {
    curseforge {
        apiKey = findProperty('curseApiToken') ?: '0'
        project {
            id = "${propertyWithFallback("curseforge_id", "curse_id_fabric")}"
            "${propertyWithFallback("curseforge_versions", "curse_versions")}".split(', ').each {
                addGameVersion "${it}"
            }
            addGameVersion 'Fabric'
            mainArtifact(jar.archiveFile) {
                def txt = changelog(1).replace('\n-', '\n\n- ')
                txt = txt + '\n\n' + "For past versions see: ${full_changelog}"
                changelog = txt
                changelogType = 'markdown'
                releaseType = 'release'
                if (mod_version.contains("beta")) {
                    releaseType = 'beta'
                }
                if (mod_version.contains("alpha")) {
                    releaseType = 'alpha'
                }
            }
            var dependencies = propertyWithFallback('curseforge_dep_fabric', 'curse_dep_fabric')
            if (!"${dependencies}".isEmpty() || project.hasProperty('optional_curseforge_dep_fabric') || project.hasProperty('optional_curse_dep_fabric')) {
                relations {
                    if (!"${dependencies}".isEmpty()) {
                        "${dependencies}".split(', ').each {
                            requiredDependency "${it}"
                        }
                    }
                    if (project.hasProperty('optional_curseforge_dep_fabric')) {
                        "${optional_curseforge_dep_fabric}".split(', ').each {
                            optionalDependency "${it}"
                        }
                    }
                    if (project.hasProperty('optional_curse_dep_fabric')) {
                        "${optional_curse_dep_fabric}".split(', ').each {
                            optionalDependency "${it}"
                        }
                    }
                }
            }
        }
    }
    tasks.getByName('curseforge').dependsOn build
}

var hasModrinth = tasks.findByName("modrinth") != null
if (hasModrinth) {
    modrinth {
        token = findProperty('modrinthApiToken') ?: '0'
        projectId = "${modrinth_id}"
        versionNumber = version
        versionName = jar.archiveFileName
        changelog = changelog(1) + '\n\n' + "For past versions see: ${full_changelog}"
        versionType = 'release'
        if (mod_version.contains("beta")) {
            versionType = 'beta'
        }
        if (mod_version.contains("alpha")) {
            versionType = 'alpha'
        }
        uploadFile = jar
        gameVersions = "${modrinth_versions}".split(', ').toList()
        loaders = ['fabric']
        dependencies {
            if (!"${modrinth_dep_fabric}".isEmpty()) {
                "${modrinth_dep_fabric}".split(', ').each {
                    required.project "${it}"
                }
            }
            if (project.hasProperty('optional_modrinth_dep_fabric')) {
                "${optional_modrinth_dep_fabric}".split(', ').each {
                    optional.project "${it}"
                }
            }
        }
    }
    tasks.getByName('modrinth').dependsOn build
}

tasks.register('cleanLocalPublish') {
    group = 'publishing'
    dependsOn ':common:clean', clean, publishToMavenLocal
    publishToMavenLocal.mustRunAfter ':common:clean', clean
}

tasks.register('cleanPublish') {
    group = 'publishing'
    dependsOn ':common:clean', clean, publish
    publish.mustRunAfter ':common:clean', clean
}

if (hasCurseforge || hasModrinth) {
    tasks.register('upload') {
        group = 'publishing'
        dependsOn ':common:clean', clean, build
        build.mustRunAfter ':common:clean', clean
        if (hasCurseforge) {
            dependsOn 'curseforge'
        }
        if (hasModrinth) {
            dependsOn 'modrinth'
        }
        doLast {
            if (project.hasProperty("notifications")) {
                notifications.add('fabric')
            }
        }
    }

    tasks.register('uploadAndPublish') {
        group = 'publishing'
        dependsOn upload, publish
        publish.mustRunAfter upload
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = project.mod_id
            suppressPomMetadataWarningsFor('runtimeElements')
        }
    }
}