plugins {
    id 'net.neoforged.moddev'
    id 'io.github.flemmli97.multiloader.changelog'
    id 'io.github.flemmli97.multiloader.common-convention'
}

neoForge {
    version = neoforge_version
    def at = project(":common").file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    validateAccessTransformers = true
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            disableIdeRun()
        }
        client {
            client()
            jvmArgument '-Dmixin.debug.export=true'
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    maven {
        name = 'Fabric'
        url = uri('https://maven.fabricmc.net')
        content {
            includeGroupByRegex('net.fabricmc')
        }
    }
}

dependencies {
    compileOnly(project(':common'))
    compileOnly(project(path: ':common', configuration: 'commonDependency'))
    compileOnly(project(path: ':fabric', configuration: 'remapCommonArtifact'))
}

processResources {
    from(project(":common").sourceSets.main.resources)
}

tasks.named('compileJava', JavaCompile) {
    source(project(":common").sourceSets.main.allSource)
}

tasks.named('sourcesJar', Jar) {
    from(project(":common").sourceSets.main.allSource)
    exclude '.cache'
}

var hasCurseforge = tasks.findByName("curseforge") != null
if (hasCurseforge) {
    curseforge {
        apiKey = findProperty('curseApiToken') ?: '0'
        project {
            id = "${curse_id_forge}"
            "${curse_versions}".split(', ').each {
                addGameVersion "${it}"
            }
            addGameVersion 'NeoForge'
            mainArtifact(jar.archiveFile) {
                def txt = changelog(1).replace('\n-', '\n\n- ')
                txt = txt + '\n\n' + "For past versions see: ${full_changelog}"
                changelog = txt
                changelogType = 'markdown'
                releaseType = 'release'
                if (mod_version.contains("beta")) {
                    releaseType = 'beta'
                }
                if (mod_version.contains("alpha")) {
                    releaseType = 'alpha'
                }
            }
            if (!"${curse_dep_forge}".isEmpty() || project.hasProperty('optional_curse_dep_forge')) {
                relations {
                    if (!"${curse_dep_forge}".isEmpty()) {
                        "${curse_dep_forge}".split(', ').each {
                            requiredDependency "${it}"
                        }
                    }
                    if (project.hasProperty('optional_curse_dep_forge')) {
                        "${optional_curse_dep_forge}".split(', ').each {
                            optionalDependency "${it}"
                        }
                    }
                }
            }
        }
    }
    tasks.getByName('curseforge').dependsOn build
}

var hasModrinth = tasks.findByName("modrinth") != null
if (hasModrinth) {
    modrinth {
        token = findProperty('modrinthApiToken') ?: '0'
        projectId = "${modrinth_id}"
        versionNumber = version
        versionName = jar.archiveFileName
        changelog = changelog(1) + '\n\n' + "For past versions see: ${full_changelog}"
        versionType = 'release'
        if (mod_version.contains("beta")) {
            versionType = 'beta'
        }
        if (mod_version.contains("alpha")) {
            versionType = 'alpha'
        }
        uploadFile = jar
        gameVersions = "${modrinth_versions}".split(', ').toList()
        loaders = ['neoforge']
        dependencies {
            if (!"${modrinth_dep_forge}".isEmpty()) {
                "${modrinth_dep_forge}".split(', ').each {
                    required.project "${it}"
                }
            }
            if (project.hasProperty('optional_modrinth_dep_forge')) {
                "${optional_modrinth_dep_forge}".split(', ').each {
                    optional.project "${it}"
                }
            }
        }
    }
    tasks.getByName('modrinth').dependsOn build
}

tasks.register('cleanLocalPublish') {
    group = 'publishing'
    dependsOn ':common:clean', clean, publishToMavenLocal
    publishToMavenLocal.mustRunAfter ':common:clean', clean
}

tasks.register('cleanPublish') {
    group = 'publishing'
    dependsOn ':common:clean', clean, publish
    publish.mustRunAfter ':common:clean', clean
}

if (hasCurseforge || hasModrinth) {
    tasks.register('upload') {
        group = 'publishing'
        dependsOn ':common:clean', clean, build
        dependsOn 'curseforge', 'modrinth'
        build.mustRunAfter ':common:clean', clean
        doLast {
            if (project.hasProperty("notifications")) {
                notifications.add('neoforge')
            }
        }
    }

    tasks.register('uploadAndPublish') {
        group = 'publishing'
        dependsOn upload, publish
        publish.mustRunAfter upload
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = project.mod_id
            suppressPomMetadataWarningsFor('runtimeElements')
        }
    }
}