plugins {
    id 'groovy-gradle-plugin'
    id 'maven-publish'
}

base.archivesName = rootProject.name
version = plugin_version
group = maven_group

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation 'com.diluv.schoomp:Schoomp:1.2.6'
}

processResources {
    filesMatching('multiloader.properties') {
        expand 'version': version
    }
}

jar {
    manifest {
        attributes([
                'Implementation-Title'  : project.name,
                'Implementation-Version': version
        ])
    }
}

publishing {
    repositories {
        def token = project.findProperty('maven.token') ?: System.getenv('BLAZING_COOP_MAVEN_TOKEN')
        if (token) {
            maven {
                url = 'https://maven.blazing-coop.net/releases'
                credentials {
                    username = project.findProperty('maven.user') ?: System.getenv('BLAZING_COOP_MAVEN_USER')
                    password = token
                }
            }
        }
        token = project.findProperty('gpr.gitlab.token') ?: System.getenv('GPR_GITLAB_TOKEN')
        if (token) {
            maven {
                url = 'https://gitlab.com/api/v4/projects/21830712/packages/maven'
                credentials {
                    username = project.findProperty('gpr.user') ?: System.getenv('GPR_USER')
                    password = token
                }
            }
        }
    }
}

publish.dependsOn clean