plugins {
    id "groovy-gradle-plugin"
    id "maven-publish"
}

base.archivesName = rootProject.name
version = plugin_version
group = maven_group

repositories {
    maven {
        name = "Fabric"
        url = uri("https://maven.fabricmc.net")
        content {
            includeGroupByRegex("net.fabricmc.*")
        }
    }
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation "com.diluv.schoomp:Schoomp:1.2.6"
    implementation "com.google.code.gson:gson:2.13.2"
    implementation "net.fabricmc:tiny-remapper:0.10.0"
    implementation "net.fabricmc:mapping-io:0.5.1"
}

processResources {
    filesMatching("multiloader.properties") {
        expand "version": version
    }
}

jar {
    manifest {
        attributes([
                "Implementation-Title"  : project.name,
                "Implementation-Version": version
        ])
    }
}

gradlePlugin {
    plugins {
        discordHook {
            id = "io.github.flemmli97.multiloader.discord_hook"
            implementationClass = "io.github.flemmli97.multiloader.DiscordHookPlugin"
        }
        common {
            id = "io.github.flemmli97.multiloader.platform-common"
            implementationClass = "io.github.flemmli97.multiloader.CommonPlugin"
        }
        fabric {
            id = "io.github.flemmli97.multiloader.platform-fabric"
            implementationClass = "io.github.flemmli97.multiloader.FabricPlugin"
        }
        legacyForge {
            id = "io.github.flemmli97.multiloader.platform-legacyforge"
            implementationClass = "io.github.flemmli97.multiloader.LegacyForgePlugin"
        }
        neoforge {
            id = "io.github.flemmli97.multiloader.platform-neoforge"
            implementationClass = "io.github.flemmli97.multiloader.NeoForgePlugin"
        }
        tinyMapper {
            id = "io.github.flemmli97.multiloader.tiny-remapper"
            implementationClass = "io.github.flemmli97.multiloader.remapper.TinyRemapperPlugin"
        }
    }
}

publishing {
    repositories {
        def token = project.findProperty("maven.token") ?: System.getenv("BLAZING_COOP_MAVEN_TOKEN")
        if (token) {
            maven {
                url = "https://maven.blazing-coop.net/releases"
                credentials {
                    username = project.findProperty("maven.user") ?: System.getenv("BLAZING_COOP_MAVEN_USER")
                    password = token
                }
            }
        }
        token = project.findProperty("gpr.gitlab.token") ?: System.getenv("GPR_GITLAB_TOKEN")
        if (token) {
            maven {
                url = "https://gitlab.com/api/v4/projects/21830712/packages/maven"
                credentials {
                    username = project.findProperty("gpr.user") ?: System.getenv("GPR_USER")
                    password = token
                }
            }
        }
    }
}

publish.dependsOn clean