architectury {
    injectInjectables = false
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
}

tasks.register('cleanLocalPublish') {
    group = 'publishing'
    dependsOn ':common:clean', clean, publishToMavenLocal
    build.mustRunAfter ':common:clean', clean
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(jar) {
                classifier null
                builtBy jar
            }
            artifact(sourcesJar) {
                classifier 'sources'
                builtBy remapSourcesJar
            }
            artifactId project.archives_base_name
        }
    }
}
