buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath rootProject.hasProperty('shadow_dep') ? shadow_dep : ["group": "com.github.johnrengelman", "name": "shadow", "version": "8.+"]
        classpath 'gradle.plugin.com.matthewprenger:CurseGradle:1.4.0'
        classpath 'com.modrinth.minotaur:Minotaur:2.+'
    }
}

apply plugin: com.modrinth.minotaur.Minotaur
apply plugin: com.github.jengelman.gradle.plugins.shadow.ShadowPlugin
apply plugin: com.matthewprenger.cursegradle.CurseGradlePlugin

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    runs {
        client {
            vmArgs '-Dmixin.debug.export=true'
        }
    }
}

ext {
    mod_meta = ['version': rootProject.version, 'loader_version': forge_loader_version, 'homepage': curse_page_forge,
                'mcversion': minecraft_version, 'forge_version': forge_version]
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle(project(path: ':common', configuration: 'transformProductionForge'))
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand mod_meta
    }
    exclude '.cache'
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

jar {
    archiveClassifier = 'dev'
}

sourcesJar {
    def commonSources = project(':common').sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
    archiveClassifier.set('sources')
}

curseforge {
    apiKey = findProperty('curseApiToken') ?: '0'

    project {
        id = "${curse_id_forge}"
        "${project.curse_versions}".split(', ').each {
            addGameVersion "${it}"
        }
        addGameVersion 'Forge'
        mainArtifact(remapJar) {
            def txt = rootProject.changelog(1).replace('\n-', '\n\n- ')
            txt = txt + '\n\n' + "For past versions see: ${project.full_changelog}"
            changelog = txt
            changelogType = 'markdown'
            releaseType = 'release'
            if (mod_version.contains("beta")) {
                releaseType = 'beta'
            }
            if (mod_version.contains("alpha")) {
                releaseType = 'alpha'
            }
        }
        if (!"${project.curse_dep_forge}".isEmpty() || project.hasProperty('optional_curse_dep_forge')) {
            relations {
                if (!"${project.curse_dep_forge}".isEmpty()) {
                    "${project.curse_dep_forge}".split(', ').each {
                        requiredDependency "${it}"
                    }
                }
                if (project.hasProperty('optional_curse_dep_forge')) {
                    "${project.optional_curse_dep_forge}".split(', ').each {
                        optionalDependency "${it}"
                    }
                }
            }
        }
    }
}
tasks.getByName('curseforge').mustRunAfter build

modrinth {
    token = findProperty('modrinthApiToken') ?: '0'
    projectId = "${modrinth_id}"
    versionNumber = version
    versionName = remapJar.archiveFileName
    changelog = rootProject.changelog(1) + '\n\n' + "For past versions see: ${project.full_changelog}"
    versionType = 'release'
    if (mod_version.contains("beta")) {
        versionType = 'beta'
    }
    if (mod_version.contains("alpha")) {
        versionType = 'alpha'
    }
    uploadFile = remapJar
    gameVersions = "${project.modrinth_versions}".split(', ').toList()
    loaders = ['forge']
    dependencies {
        if (!"${project.modrinth_dep_forge}".isEmpty()) {
            "${project.modrinth_dep_forge}".split(', ').each {
                required.project "${it}"
            }
        }
        if (project.hasProperty('optional_modrinth_dep_forge')) {
            "${project.optional_modrinth_dep_forge}".split(', ').each {
                optional.project "${it}"
            }
        }
    }
}
tasks.getByName('modrinth').dependsOn build

tasks.register('cleanLocalPublish') {
    group = 'publishing'
    dependsOn ':common:clean', clean, publishToMavenLocal
    publishToMavenLocal.mustRunAfter ':common:clean', clean
}

tasks.register('upload') {
    group = 'publishing'
    dependsOn ':common:clean', clean, build
    dependsOn 'curseforge', 'modrinth'
    build.mustRunAfter ':common:clean', clean
    doLast {
        notifications.add('forge')
    }
}

tasks.register('uploadAndPublish') {
    group = 'publishing'
    dependsOn upload, publish
    publish.mustRunAfter upload
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(remapJar) {
                classifier null
                builtBy remapJar
            }
            artifact(sourcesJar) {
                classifier 'sources'
                builtBy remapSourcesJar
            }
            artifactId project.archives_base_name
        }
    }
}
